services:
  postgres:
    image: postgres:latest
    container_name: marcapasso3d-db
    environment:
      POSTGRES_DB: marcapasso3d
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: sua_senha
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql

volumes:
  pgdata: