# Banco de dados PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/marcapasso3d
spring.datasource.username=admin
spring.datasource.password=sua_senha
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update

# Segurança JWT
jwt.secret=marcapasso3d-chave-sade-likeatattoo
jwt.expiration-ms=3600000

# Chave da API da IA (fica aqui no servidor — nunca exposta ao frontend)
# O ChatIAService lê essa chave com @Value("${ia.api.key}")
ia.api.key=apf_buyk5oglfcv7c05x37xn5kdc

mercadopago.access-token=APP_USR-131556045525239-061000-accc9b283c94b37457c961539580eaad-3464418934
mercadopago.sandbox=true
mercadopago.payer-email-teste=TESTUSER865097...@testuser.com
app.frontend-url=http://localhost:5173

telegram.bot-token=8418848888:AAHyw0Cdjk5p3Y8HwDEzV7TphQ1bE4mZID0
telegram.chat-id=1850714051

telegram.bot-token=8813023578:AAFSVYNQcZggkJqxYQ6BjCQqEEGbJHZ44L4
telegram.chat-id=1850714051
