CREATE TABLE IF NOT EXISTS produtos (
    id_produto BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    descricao TEXT,
    resumo_ia TEXT,
    preco NUMERIC(19,2) NOT NULL,
    imagem_principal VARCHAR(255),
    personalizavel BOOLEAN,
    categoria VARCHAR(255),
    material VARCHAR(255),
    estoque INTEGER,
    total_vendas INTEGER DEFAULT 0
);

CREATE TABLE IF NOT EXISTS usuarios (
    id_usuario BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome VARCHAR(255) NOT NULL,
    email VARCHAR(255) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    telefone VARCHAR(255),
    cpf VARCHAR(255) UNIQUE,
    role VARCHAR(50) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,
    criado_em TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS favoritos (
    id_favorito BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL UNIQUE,
    CONSTRAINT fk_favoritos_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS favorito_produtos (
    id_favorito BIGINT NOT NULL,
    id_produto BIGINT NOT NULL,
    CONSTRAINT pk_favorito_produtos PRIMARY KEY (id_favorito, id_produto),
    CONSTRAINT fk_favorito_produtos_favorito
        FOREIGN KEY (id_favorito)
        REFERENCES favoritos (id_favorito)
        ON DELETE CASCADE,
    CONSTRAINT fk_favorito_produtos_produto
        FOREIGN KEY (id_produto)
        REFERENCES produtos (id_produto)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS carrinhos (
    id_carrinho BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    criado_em DATE,
    CONSTRAINT fk_carrinhos_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS carrinho_itens (
    id_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_carrinho BIGINT NOT NULL,
    id_produto BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario NUMERIC(19,2) NOT NULL,
    CONSTRAINT fk_carrinho_itens_carrinho
        FOREIGN KEY (id_carrinho)
        REFERENCES carrinhos (id_carrinho)
        ON DELETE CASCADE,
    CONSTRAINT fk_carrinho_itens_produto
        FOREIGN KEY (id_produto)
        REFERENCES produtos (id_produto)
        ON DELETE RESTRICT
);

CREATE TABLE IF NOT EXISTS enderecos (
    id_endereco BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    nome VARCHAR(255) NOT NULL,
    rua VARCHAR(255) NOT NULL,
    numero VARCHAR(255) NOT NULL,
    complemento VARCHAR(255),
    bairro VARCHAR(255) NOT NULL,
    cidade VARCHAR(255) NOT NULL,
    estado VARCHAR(255) NOT NULL,
    cep VARCHAR(255) NOT NULL,
    CONSTRAINT fk_enderecos_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS cupons (
    id_cupom BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nome_cupom VARCHAR(255) NOT NULL UNIQUE,
    valor_desconto NUMERIC(10,2) NOT NULL,
    tipo_validade VARCHAR(50) NOT NULL,
    data_expiracao DATE,
    criado_em TIMESTAMP,
    atualizado_em TIMESTAMP
);

CREATE TABLE IF NOT EXISTS encomendas (
    id_encomenda BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_usuario BIGINT NOT NULL,
    numero_pedido VARCHAR(255) NOT NULL UNIQUE,
    data_hora TIMESTAMP NOT NULL,
    status VARCHAR(50) NOT NULL,
    subtotal NUMERIC(19,2) NOT NULL,
    frete NUMERIC(19,2) NOT NULL,
    desconto NUMERIC(19,2) NOT NULL,
    desconto_cupom NUMERIC(19,2) NOT NULL,
    total NUMERIC(19,2) NOT NULL,
    forma_pagamento VARCHAR(255) NOT NULL,
    tipo_pagamento VARCHAR(255),
    bandeira_cartao VARCHAR(255),
    parcelamento VARCHAR(255),
    titular_cartao VARCHAR(255),
    cpf_titular VARCHAR(255),
    bin_cartao VARCHAR(255),
    end_rua VARCHAR(255),
    end_numero VARCHAR(255),
    end_complemento VARCHAR(255),
    end_bairro VARCHAR(255),
    end_cidade VARCHAR(255),
    end_estado VARCHAR(255),
    end_cep VARCHAR(255),
    cliente_nome VARCHAR(255),
    cliente_email VARCHAR(255),
    cliente_cpf VARCHAR(255),
    CONSTRAINT fk_encomendas_usuario
        FOREIGN KEY (id_usuario)
        REFERENCES usuarios (id_usuario)
        ON DELETE CASCADE
);

CREATE TABLE IF NOT EXISTS encomenda_itens (
    id_item BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    id_encomenda BIGINT NOT NULL,
    id_produto BIGINT NOT NULL,
    quantidade INTEGER NOT NULL,
    preco_unitario NUMERIC(19,2) NOT NULL,
    CONSTRAINT fk_encomenda_itens_encomenda
        FOREIGN KEY (id_encomenda)
        REFERENCES encomendas (id_encomenda)
        ON DELETE CASCADE,
    CONSTRAINT fk_encomenda_itens_produto
        FOREIGN KEY (id_produto)
        REFERENCES produtos (id_produto)
        ON DELETE RESTRICT
);